# Generated by Django 5.2 on 2026-02-22 08:14

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('agent_id', models.CharField(editable=False, max_length=4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('phone_no', models.CharField(max_length=13)),
            ],
            options={
                'db_table': 'AGENT',
            },
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('bank_id', models.CharField(editable=False, max_length=4, primary_key=True, serialize=False)),
                ('bank_acronym', models.CharField(max_length=6, unique=True)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'BANK',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.CharField(editable=False, max_length=4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('contact_person', models.CharField(max_length=50)),
                ('phone_no', models.CharField(max_length=13)),
                ('address', models.CharField(max_length=150)),
                ('area', models.CharField(blank=True, choices=[('No Selection', 'No Selection'), ('Caloocan, Metro Manila', 'Caloocan, Metro Manila'), ('Las Piñas, Metro Manila', 'Las Piñas, Metro Manila'), ('Makati, Metro Manila', 'Makati, Metro Manila'), ('Malabon, Metro Manila', 'Malabon, Metro Manila'), ('Mandaluyong, Metro Manila', 'Mandaluyong, Metro Manila'), ('Manila, Metro Manila', 'Manila, Metro Manila'), ('Marikina, Metro Manila', 'Marikina, Metro Manila'), ('Muntinlupa, Metro Manila', 'Muntinlupa, Metro Manila'), ('Navotas, Metro Manila', 'Navotas, Metro Manila'), ('Parañaque, Metro Manila', 'Parañaque, Metro Manila'), ('Pasay, Metro Manila', 'Pasay, Metro Manila'), ('Pasig, Metro Manila', 'Pasig, Metro Manila'), ('Quezon City, Metro Manila', 'Quezon City, Metro Manila'), ('San Juan, Metro Manila', 'San Juan, Metro Manila'), ('Taguig, Metro Manila', 'Taguig, Metro Manila'), ('Valenzuela, Metro Manila', 'Valenzuela, Metro Manila'), ('Pateros, Metro Manila', 'Pateros, Metro Manila'), ('Alaminos, Pangasinan', 'Alaminos, Pangasinan'), ('Batac, Ilocos Norte', 'Batac, Ilocos Norte'), ('Candon, Ilocos Sur', 'Candon, Ilocos Sur'), ('Dagupan, Pangasinan', 'Dagupan, Pangasinan'), ('Laoag, Ilocos Norte', 'Laoag, Ilocos Norte'), ('San Carlos, Pangasinan', 'San Carlos, Pangasinan'), ('San Fernando, La Union', 'San Fernando, La Union'), ('Urdaneta, Pangasinan', 'Urdaneta, Pangasinan'), ('Vigan, Ilocos Sur', 'Vigan, Ilocos Sur'), ('Cauayan, Isabela', 'Cauayan, Isabela'), ('Ilagan, Isabela', 'Ilagan, Isabela'), ('Santiago, Isabela', 'Santiago, Isabela'), ('Tuguegarao, Cagayan', 'Tuguegarao, Cagayan'), ('Angeles City, Pampanga', 'Angeles City, Pampanga'), ('Balanga, Bataan', 'Balanga, Bataan'), ('Cabanatuan, Nueva Ecija', 'Cabanatuan, Nueva Ecija'), ('Gapan, Nueva Ecija', 'Gapan, Nueva Ecija'), ('Mabalacat, Pampanga', 'Mabalacat, Pampanga'), ('Malolos, Bulacan', 'Malolos, Bulacan'), ('Meycauayan, Bulacan', 'Meycauayan, Bulacan'), ('Muñoz, Nueva Ecija', 'Muñoz, Nueva Ecija'), ('Olongapo, Zambales', 'Olongapo, Zambales'), ('Palayan, Nueva Ecija', 'Palayan, Nueva Ecija'), ('San Fernando, Pampanga', 'San Fernando, Pampanga'), ('San Jose, Nueva Ecija', 'San Jose, Nueva Ecija'), ('San Jose del Monte, Bulacan', 'San Jose del Monte, Bulacan'), ('Tarlac City, Tarlac', 'Tarlac City, Tarlac'), ('Antipolo, Rizal', 'Antipolo, Rizal'), ('Bacoor, Cavite', 'Bacoor, Cavite'), ('Batangas City, Batangas', 'Batangas City, Batangas'), ('Biñan, Laguna', 'Biñan, Laguna'), ('Cabuyao, Laguna', 'Cabuyao, Laguna'), ('Calamba, Laguna', 'Calamba, Laguna'), ('Calaca, Batangas', 'Calaca, Batangas'), ('Carmona, Cavite', 'Carmona, Cavite'), ('Cavite City, Cavite', 'Cavite City, Cavite'), ('Dasmariñas, Cavite', 'Dasmariñas, Cavite'), ('General Trias, Cavite', 'General Trias, Cavite'), ('Imus, Cavite', 'Imus, Cavite'), ('Lipa, Batangas', 'Lipa, Batangas'), ('Lucena, Quezon', 'Lucena, Quezon'), ('San Pablo, Laguna', 'San Pablo, Laguna'), ('San Pedro, Laguna', 'San Pedro, Laguna'), ('Santa Rosa, Laguna', 'Santa Rosa, Laguna'), ('Santo Tomas, Batangas', 'Santo Tomas, Batangas'), ('Tagaytay, Cavite', 'Tagaytay, Cavite'), ('Tanauan, Batangas', 'Tanauan, Batangas'), ('Tayabas, Quezon', 'Tayabas, Quezon'), ('Trece Martires, Cavite', 'Trece Martires, Cavite'), ('Calapan, Oriental Mindoro', 'Calapan, Oriental Mindoro'), ('Puerto Princesa, Palawan', 'Puerto Princesa, Palawan'), ('Iriga, Camarines Sur', 'Iriga, Camarines Sur'), ('Legazpi, Albay', 'Legazpi, Albay'), ('Ligao, Albay', 'Ligao, Albay'), ('Masbate City, Masbate', 'Masbate City, Masbate'), ('Naga, Camarines Sur', 'Naga, Camarines Sur'), ('Sorsogon City, Sorsogon', 'Sorsogon City, Sorsogon'), ('Tabaco, Albay', 'Tabaco, Albay'), ('Bacolod, Negros Occidental', 'Bacolod, Negros Occidental'), ('Bago, Negros Occidental', 'Bago, Negros Occidental'), ('Cadiz, Negros Occidental', 'Cadiz, Negros Occidental'), ('Escalante, Negros Occidental', 'Escalante, Negros Occidental'), ('Himamaylan, Negros Occidental', 'Himamaylan, Negros Occidental'), ('Iloilo City, Iloilo', 'Iloilo City, Iloilo'), ('Kabankalan, Negros Occidental', 'Kabankalan, Negros Occidental'), ('La Carlota, Negros Occidental', 'La Carlota, Negros Occidental'), ('Passi, Iloilo', 'Passi, Iloilo'), ('Roxas, Capiz', 'Roxas, Capiz'), ('Sagay, Negros Occidental', 'Sagay, Negros Occidental'), ('San Carlos, Negros Occidental', 'San Carlos, Negros Occidental'), ('Silay, Negros Occidental', 'Silay, Negros Occidental'), ('Sipalay, Negros Occidental', 'Sipalay, Negros Occidental'), ('Talisay, Negros Occidental', 'Talisay, Negros Occidental'), ('Victorias, Negros Occidental', 'Victorias, Negros Occidental'), ('Bais, Negros Oriental', 'Bais, Negros Oriental'), ('Bayawan, Negros Oriental', 'Bayawan, Negros Oriental'), ('Bogo, Cebu', 'Bogo, Cebu'), ('Canlaon, Negros Oriental', 'Canlaon, Negros Oriental'), ('Carcar, Cebu', 'Carcar, Cebu'), ('Cebu City, Cebu', 'Cebu City, Cebu'), ('Danao, Cebu', 'Danao, Cebu'), ('Dumaguete, Negros Oriental', 'Dumaguete, Negros Oriental'), ('Guihulngan, Negros Oriental', 'Guihulngan, Negros Oriental'), ('Lapu-Lapu, Cebu', 'Lapu-Lapu, Cebu'), ('Mandaue, Cebu', 'Mandaue, Cebu'), ('Naga, Cebu', 'Naga, Cebu'), ('San Fernando, Cebu', 'San Fernando, Cebu'), ('Talisay, Cebu', 'Talisay, Cebu'), ('Tanjay, Negros Oriental', 'Tanjay, Negros Oriental'), ('Toledo, Cebu', 'Toledo, Cebu'), ('Baybay, Leyte', 'Baybay, Leyte'), ('Borongan, Eastern Samar', 'Borongan, Eastern Samar'), ('Calbayog, Samar', 'Calbayog, Samar'), ('Catbalogan, Samar', 'Catbalogan, Samar'), ('Maasin, Southern Leyte', 'Maasin, Southern Leyte'), ('Ormoc, Leyte', 'Ormoc, Leyte'), ('Tacloban, Leyte', 'Tacloban, Leyte'), ('Dapitan, Zamboanga del Norte', 'Dapitan, Zamboanga del Norte'), ('Dipolog, Zamboanga del Norte', 'Dipolog, Zamboanga del Norte'), ('Isabela, Basilan', 'Isabela, Basilan'), ('Pagadian, Zamboanga del Sur', 'Pagadian, Zamboanga del Sur'), ('Zamboanga City, Zamboanga del Sur', 'Zamboanga City, Zamboanga del Sur'), ('Cagayan de Oro, Misamis Oriental', 'Cagayan de Oro, Misamis Oriental'), ('El Salvador, Misamis Oriental', 'El Salvador, Misamis Oriental'), ('Gingoog, Misamis Oriental', 'Gingoog, Misamis Oriental'), ('Iligan, Lanao del Norte', 'Iligan, Lanao del Norte'), ('Malaybalay, Bukidnon', 'Malaybalay, Bukidnon'), ('Oroquieta, Misamis Occidental', 'Oroquieta, Misamis Occidental'), ('Ozamiz, Misamis Occidental', 'Ozamiz, Misamis Occidental'), ('Tangub, Misamis Occidental', 'Tangub, Misamis Occidental'), ('Valencia, Bukidnon', 'Valencia, Bukidnon'), ('Davao City, Davao del Sur', 'Davao City, Davao del Sur'), ('Digos, Davao del Sur', 'Digos, Davao del Sur'), ('Mati, Davao Oriental', 'Mati, Davao Oriental'), ('Panabo, Davao del Norte', 'Panabo, Davao del Norte'), ('Samal, Davao del Norte', 'Samal, Davao del Norte'), ('Tagum, Davao del Norte', 'Tagum, Davao del Norte'), ('General Santos, South Cotabato', 'General Santos, South Cotabato'), ('Kidapawan, Cotabato', 'Kidapawan, Cotabato'), ('Koronadal, South Cotabato', 'Koronadal, South Cotabato'), ('Tacurong, Sultan Kudarat', 'Tacurong, Sultan Kudarat'), ('Bislig, Surigao del Sur', 'Bislig, Surigao del Sur'), ('Butuan, Agusan del Norte', 'Butuan, Agusan del Norte'), ('Cabadbaran, Agusan del Norte', 'Cabadbaran, Agusan del Norte'), ('Surigao City, Surigao del Norte', 'Surigao City, Surigao del Norte'), ('Tandag, Surigao del Sur', 'Tandag, Surigao del Sur'), ('Baguio, Benguet', 'Baguio, Benguet'), ('Tabuk, Kalinga', 'Tabuk, Kalinga'), ('Cotabato City, Maguindanao del Norte', 'Cotabato City, Maguindanao del Norte'), ('Lamitan, Basilan', 'Lamitan, Basilan'), ('Marawi, Lanao del Sur', 'Marawi, Lanao del Sur')], default='No Selection', max_length=100)),
            ],
            options={
                'db_table': 'CUSTOMER',
            },
        ),
        migrations.CreateModel(
            name='PaymentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_record_no', models.CharField(db_column='Payment_Record_No', editable=False, max_length=4)),
                ('payment_date', models.DateField(db_column='Payment_Date', default=django.utils.timezone.localdate)),
                ('amount', models.DecimalField(db_column='Amount', decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('days', models.IntegerField(db_column='Days', default=0, editable=False)),
                ('payment_type', models.CharField(choices=[('Cash', 'Cash'), ('Cheque', 'Cheque')], db_column='Payment_Type', max_length=10)),
            ],
            options={
                'db_table': 'PAYMENT_RECORD',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.CharField(editable=False, max_length=5, primary_key=True, serialize=False)),
                ('product_code', models.CharField(max_length=10, unique=True)),
                ('description', models.CharField(max_length=150)),
                ('quantity', models.IntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=8)),
            ],
            options={
                'db_table': 'PRODUCTS',
            },
        ),
        migrations.CreateModel(
            name='ChequePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cq_date', models.DateField(db_column='CQ_Date', default=django.utils.timezone.localdate)),
                ('cheque_no', models.CharField(db_column='Cheque_No', max_length=10)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Cleared', 'Cleared'), ('Bounced', 'Bounced')], db_column='Status', default='Pending', max_length=10)),
                ('bank', models.ForeignKey(db_column='Bank_ID', on_delete=django.db.models.deletion.PROTECT, related_name='cheque_payments', to='payroll_app.bank')),
                ('payment_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cheque_detail', to='payroll_app.paymentrecord')),
            ],
            options={
                'db_table': 'CHEQUE_PAYMENT',
            },
        ),
        migrations.CreateModel(
            name='SalesInvoice',
            fields=[
                ('invoice_id', models.CharField(db_column='Invoice_ID', editable=False, max_length=8, primary_key=True, serialize=False)),
                ('invoice_no', models.CharField(db_column='Invoice_No', editable=False, max_length=10, unique=True)),
                ('date', models.DateField(db_column='Date', default=django.utils.timezone.localdate)),
                ('plate_no', models.CharField(blank=True, db_column='Plate_No', default='', max_length=10)),
                ('payment_status', models.CharField(choices=[('Unpaid', 'Unpaid'), ('Partial', 'Partial'), ('Paid', 'Paid')], db_column='Payment_Status', default='Unpaid', editable=False, max_length=10)),
                ('partial_payment', models.DecimalField(db_column='Partial_Payment', decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=10)),
                ('terms', models.CharField(blank=True, db_column='Terms', max_length=50, null=True)),
                ('remarks', models.CharField(blank=True, db_column='Remarks', max_length=255, null=True)),
                ('delivery_status', models.BooleanField(db_column='Delivery_Status', default=False)),
                ('grand_total', models.DecimalField(db_column='Grand_Total', decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=12)),
                ('discount', models.DecimalField(blank=True, db_column='Discount', decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('remaining_balance', models.DecimalField(db_column='Remaining_Balance', decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=10)),
                ('agent', models.ForeignKey(db_column='Agent_ID', on_delete=django.db.models.deletion.PROTECT, related_name='sales_invoices', to='payroll_app.agent')),
                ('customer', models.ForeignKey(db_column='Customer_ID', on_delete=django.db.models.deletion.PROTECT, related_name='sales_invoices', to='payroll_app.customer')),
            ],
            options={
                'db_table': 'SALES_TRANSACTION',
            },
        ),
        migrations.AddField(
            model_name='paymentrecord',
            name='invoice',
            field=models.ForeignKey(db_column='Invoice_ID', on_delete=django.db.models.deletion.CASCADE, related_name='payment_records', to='payroll_app.salesinvoice'),
        ),
        migrations.CreateModel(
            name='OrderRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_quantity', models.PositiveIntegerField(db_column='Order_Quantity', default=0)),
                ('order_price_per_unit', models.DecimalField(db_column='Order_Price_per_Unit', decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('rate', models.DecimalField(db_column='Rate', decimal_places=2, default=Decimal('1.00'), max_digits=3, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('1.00'))])),
                ('total_price', models.DecimalField(db_column='Total_Price', decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=12)),
                ('product', models.ForeignKey(db_column='Product_ID', on_delete=django.db.models.deletion.PROTECT, related_name='order_records', to='payroll_app.product')),
                ('invoice', models.ForeignKey(db_column='Invoice_ID', on_delete=django.db.models.deletion.CASCADE, related_name='order_records', to='payroll_app.salesinvoice')),
            ],
            options={
                'db_table': 'ORDER_RECORD',
            },
        ),
        migrations.CreateModel(
            name='ReturnRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_quantity', models.PositiveIntegerField(db_column='Return_Quantity', default=0)),
                ('return_price_per_unit', models.DecimalField(db_column='Return_Price_per_Unit', decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('rate', models.DecimalField(db_column='Rate', decimal_places=2, default=Decimal('1.00'), max_digits=3, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('1.00'))])),
                ('total_price', models.DecimalField(db_column='Total_Price', decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=12)),
                ('product', models.ForeignKey(db_column='Product_ID', on_delete=django.db.models.deletion.PROTECT, related_name='return_records', to='payroll_app.product')),
                ('invoice', models.ForeignKey(db_column='Invoice_ID', on_delete=django.db.models.deletion.CASCADE, related_name='return_records', to='payroll_app.salesinvoice')),
            ],
            options={
                'db_table': 'RETURN_RECORD',
                'constraints': [models.UniqueConstraint(fields=('invoice', 'product'), name='uq_return_invoice_product')],
            },
        ),
        migrations.AddConstraint(
            model_name='paymentrecord',
            constraint=models.UniqueConstraint(fields=('invoice', 'payment_record_no'), name='uq_payment_invoice_recordno'),
        ),
        migrations.AddConstraint(
            model_name='orderrecord',
            constraint=models.UniqueConstraint(fields=('invoice', 'product'), name='uq_order_invoice_product'),
        ),
    ]
