# Generated by Django 5.2 on 2026-02-22 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoice',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_column='Deleted_At', null=True),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='is_deleted',
            field=models.BooleanField(db_column='Is_Deleted', default=False),
        ),
    ]
