# Generated by Django 5.2 on 2025-11-24 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_app', '0003_customer_product_salesinvoice_invoiceitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='customer_name',
            new_name='company_name',
        ),
    ]
