# Generated by Django 5.2 on 2025-11-27 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_app', '0007_bank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bank',
            name='branch',
        ),
    ]
