# Generated by Django 5.2 on 2025-11-27 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_app', '0008_remove_bank_branch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payslip',
            name='id_number',
        ),
        migrations.RemoveField(
            model_name='purchaseinvoice',
            name='payment_amount',
        ),
        migrations.RemoveField(
            model_name='purchaseinvoice',
            name='total_amount',
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='bank',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='bounced',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='cash_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='cheque_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='cheque_no',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='grand_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='invoice_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='payment_cash',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='payment_cheque',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='amount_due',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='invoice_number',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='payment_type',
            field=models.CharField(default='unpaid', max_length=20),
        ),
        migrations.CreateModel(
            name='PurchaseInvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('quantity', models.IntegerField(default=1)),
                ('unit', models.CharField(default='PCS', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rate', models.DecimalField(decimal_places=2, default=1, max_digits=6)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='payroll_app.purchaseinvoice')),
            ],
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='Payslip',
        ),
    ]
