# Generated by Django 5.2 on 2025-11-27 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_app', '0009_remove_payslip_id_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesinvoice',
            name='payment_amount',
        ),
        migrations.RemoveField(
            model_name='salesinvoice',
            name='payment_type',
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='cash_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='payment_cash',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='payment_cheque',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='payment_status',
            field=models.CharField(default='unpaid', max_length=20),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payroll_app.bank'),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='cheque_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='invoice_number',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='plate_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
