# Generated by Django 5.2 on 2025-11-27 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_app', '0010_remove_salesinvoice_payment_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesinvoice',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payroll_app.bank'),
        ),
    ]
