# Generated by Django 5.2 on 2025-11-27 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_app', '0011_alter_salesinvoice_bank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesinvoice',
            name='cash_date',
        ),
        migrations.RemoveField(
            model_name='salesinvoice',
            name='payment_status',
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='payment_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='payment_type',
            field=models.CharField(choices=[('cash', 'Cash'), ('cheque', 'Cheque'), ('unpaid', 'Unpaid')], default='unpaid', max_length=10),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='bank',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='cheque_no',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='invoice_number',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='plate_no',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
