# Generated by Django 5.2 on 2025-11-27 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_app', '0012_remove_salesinvoice_cash_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesinvoice',
            name='payment_cash',
        ),
        migrations.RemoveField(
            model_name='salesinvoice',
            name='payment_cheque',
        ),
    ]
