# Generated by Django 5.2 on 2025-11-28 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_app', '0013_remove_salesinvoice_payment_cash_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bank',
        ),
        migrations.RemoveField(
            model_name='purchaseinvoice',
            name='amount_due',
        ),
        migrations.RemoveField(
            model_name='purchaseinvoice',
            name='bank',
        ),
        migrations.RemoveField(
            model_name='purchaseinvoice',
            name='bounced',
        ),
        migrations.RemoveField(
            model_name='purchaseinvoice',
            name='cash_date',
        ),
        migrations.RemoveField(
            model_name='purchaseinvoice',
            name='cheque_date',
        ),
        migrations.RemoveField(
            model_name='purchaseinvoice',
            name='cheque_no',
        ),
        migrations.RemoveField(
            model_name='purchaseinvoice',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='salesinvoice',
            name='amount_due',
        ),
        migrations.RemoveField(
            model_name='salesinvoice',
            name='bank',
        ),
        migrations.RemoveField(
            model_name='salesinvoice',
            name='bounced',
        ),
        migrations.RemoveField(
            model_name='salesinvoice',
            name='cheque_date',
        ),
        migrations.RemoveField(
            model_name='salesinvoice',
            name='cheque_no',
        ),
        migrations.RemoveField(
            model_name='salesinvoice',
            name='discount_received',
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='payment_type',
            field=models.CharField(choices=[('cash', 'Cash'), ('cheque', 'Cheque')], default='cash', max_length=10),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='payment_type',
            field=models.CharField(choices=[('cash', 'Cash'), ('cheque', 'Cheque')], default='cash', max_length=10),
        ),
    ]
