# Generated by Django 5.2 on 2025-11-28 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_app', '0014_delete_bank_remove_purchaseinvoice_amount_due_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoiceitem',
            name='rate',
        ),
        migrations.RemoveField(
            model_name='purchaseinvoice',
            name='payment_cash',
        ),
        migrations.RemoveField(
            model_name='purchaseinvoice',
            name='payment_cheque',
        ),
        migrations.RemoveField(
            model_name='purchaseinvoiceitem',
            name='rate',
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='amount_due',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='amount_due',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='discount_received',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='plate_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
