# Generated by Django 5.1.5 on 2026-02-17 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_app', '0016_agent_bank_remove_purchaseinvoice_supplier_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentrecord',
            old_name='payment_date',
            new_name='date',
        ),
    ]
